FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Directory.Build.props", "."]
COPY ["src/Gateway/EmployeeManagement.Gateway/EmployeeManagement.Gateway.csproj", "src/Gateway/EmployeeManagement.Gateway/"]
RUN dotnet restore "src/Gateway/EmployeeManagement.Gateway/EmployeeManagement.Gateway.csproj"
COPY . .
RUN dotnet publish "src/Gateway/EmployeeManagement.Gateway/EmployeeManagement.Gateway.csproj" -c Release -o /app/publish --no-restore

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "EmployeeManagement.Gateway.dll"]
